//Download VS Code REST CLIENT extension in order to use the requests below
//Backend needs to be up and running ('npm run dev' in backend directory)
###
GET http://localhost:3001/api/players

###
POST http://localhost:3001/api/players
Content-Type: application/json

{
	"name": "Player 4",
	"password": "30984308"
}